apimServiceName: prod-apim-apiops
namedValues:
  - name: environment
    properties:
      displayName: environment
      value: "prod"
  - name: mysecretvalue
    properties:
      displayName: mysecretvalue
      keyVault:
        identityClientId: 6af340e3-cd79-4857-8f22-08745950e470
        secretIdentifier: [your url here]
  - name: testSecret
    properties:
      displayName: testSecret
      value: "_bb8Q~uE120oEzmb3hn1AT8s5aKPkNgTzE1eycqk"
  - name: helloworldfromfuncapp-key
    properties:
      displayName: helloworldfromfuncapp-key
      value: "{#helloworldfromfuncappkey#}"
  - name: 634e022983908257b35630b0
    properties:
      displayName: helloworldfromlogicapp_manual-invoke_634e022983908257b35630b0
      value: "{#helloworldfromlogicapp#}"  
loggers:
    - name: apim-lab-insights
      properties:
        loggerType: applicationInsights
        description: prod application insights
        resourceId: "/subscriptions/9dd76f4a-3f5b-45fb-8f36-81a5e0971bed/resourceGroups/prod-apiops/providers/microsoft.insights/components/apim-lab-prod-insights"
        credentials:
          instrumentationKey: "{{Logger-Credentials--62825ade46346113589affc1}}"
        isBuffered: true
diagnostics:
   - name: applicationinsights
     properties:
       verbosity: Error
       loggerId: "/subscriptions/9dd76f4a-3f5b-45fb-8f36-81a5e0971bed/resourceGroups/prod-apiops/providers/Microsoft.ApiManagement/service/apim-prod-wk-05102022/loggers/apim-lab-prod-insights"

apis:
  - name: echo-api
    diagnostics:
      - name: applicationinsights
        properties:
          verbosity: Error
          loggerId: "/subscriptions/9dd76f4a-3f5b-45fb-8f36-81a5e0971bed/resourceGroups/prod-apiops/providers/Microsoft.ApiManagement/service/apim-prod-wk-05102022/loggers/apim-lab-prod-insights"